<?php $this->partial('shared/header'); ?>
<style>.table>thead>tr>th{ vertical-align: middle; }</style>
<div class="container">
    <div class="row">
        <div class="col-md-3">
        
            <form id="ga-filter">
                <?= $this->form->field('time-start'); ?>
                <?= $this->form->field('time-end'); ?>
                <?= $this->form->field('type'); ?>
                <div class="row">
                    <div class="col-md-8">
                        <?= $this->form->field('group'); ?>
                    </div>
                    <div class="col-md-4">
                        <div class="text-right">
                            <button class="btn btn-block btn-default">Filter</button>
                        </div>
                    </div>
                </div>
            </form>
            
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h3><?= $title ?></h3>
            </div>
            
            <?php if($error): ?>
            <div class="alert alert-danger"><strong>Error!</strong> <?= $error ?></div>
            <?php else: ?>
            <div id="graph"></div>
            <div id="resume" class="hidden">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2" id="resume-info" class="text-center"></th>
                            <th colspan="2" class="text-center">Pageviews</th>
                            <th colspan="2" class="text-center">Sessions</th>
                            <th colspan="2" class="text-center">Users</th>
                        </tr>
                        <tr>
                            <th>Total</th>
                            <th>Average</th>
                            <th>Total</th>
                            <th>Average</th>
                            <th>Total</th>
                            <th>Average</th>
                        </tr>
                    </thead>
                    <tbody id="resume-items"></tbody>
                </table>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>window.MyGA={token:'<?= $token ?>',view:'<?= $ga_view ?>'};</script>

<?php $this->partial('shared/footer'); ?>