<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
        
            <form id="ga-filter">
                <?= $this->form->field('time-start'); ?>
                <?= $this->form->field('time-end'); ?>
                <div class="row">
                    <div class="col-md-8">
                        <?= $this->form->field('group'); ?>
                    </div>
                    <div class="col-md-4">
                        <div class="text-right">
                            <button class="btn btn-block btn-default">Filter</button>
                        </div>
                    </div>
                </div>
            </form>
            
            <hr>
            
            <div class="panel panel-default">
                <div class="panel-heading">Total</div>
                <table class="table table-bordered">
                    <tbody id="resume-total"></tbody>
                </table>
            </div>
            
            <div class="panel panel-default">
                <div class="panel-heading">Average</div>
                <table class="table table-bordered">
                    <tbody id="resume-average"></tbody>
                </table>
            </div>
            
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h3><?= $title ?></h3>
            </div>
            
            <?php if($error): ?>
            <div class="alert alert-danger"><strong>Error!</strong> <?= $error ?></div>
            <?php else: ?>
            <div id="graph"></div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>window.MyGA={token:'<?= $token ?>',view:'<?= $ga_view ?>'};</script>

<?php $this->partial('shared/footer'); ?>